/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#006948',
        'primary-container': '#00855d',
        'on-primary': '#ffffff',
        'on-primary-container': '#f5fff7',
        'primary-fixed': '#85f8c4',
        'primary-fixed-dim': '#68dba9',
        secondary: '#2b6954',
        'secondary-container': '#adedd3',
        'on-secondary-container': '#306d58',
        'secondary-fixed': '#b0f0d6',
        tertiary: '#006194',
        'tertiary-container': '#007bb9',
        'on-tertiary-container': '#fdfcff',
        'tertiary-fixed': '#cce5ff',
        'on-tertiary-fixed-variant': '#004b73',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#3d4a42',
        outline: '#6d7a72',
        'outline-variant': '#bccac0',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        // semantic tier colors
        amber: '#d97706',
        'amber-soft': '#fffbeb',
        rose: '#e11d48',
        'rose-soft': '#fff1f2',
        emerald: '#059669',
        'emerald-soft': '#ecfdf5',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      boxShadow: {
        card: '0 4px 20px -2px rgba(15, 23, 42, 0.06), 0 1px 3px 0 rgba(15, 23, 42, 0.04)',
        raised: '0 10px 30px -6px rgba(15, 23, 42, 0.14), 0 2px 6px 0 rgba(15, 23, 42, 0.05)',
      },
      spacing: {
        gutter: '1.5rem',
        margin: '2rem',
      },
    },
  },
  plugins: [],
};
