// Optional LLM upgrade layer. If OPENAI_API_KEY is present, chat replies are
// generated by the LLM, grounded with the user's live stats. Without a key,
// the caller falls back to the rule-based engine — the bot always works.

const OPENAI_URL = 'https://api.openai.com/v1/chat/completions';

export function llmEnabled() {
  return Boolean(process.env.OPENAI_API_KEY);
}

export async function askLLM({ message, history = [], stats }) {
  if (!llmEnabled()) return null;
  try {
    const res = await fetch(OPENAI_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
        max_tokens: 300,
        messages: [
          {
            role: 'system',
            content:
              `You are a friendly carbon coach in a footprint tracker app. Be concise (under 120 words), encouraging, never shaming. ` +
              `The user's live data: ${JSON.stringify(stats)}. ` +
              `Emission factors: car 0.2 kg/km, bus 0.08 kg/km, flight 0.25 kg/km, electricity 0.8 kg/kWh, veg meal 0.5 kg, non-veg meal 2.0 kg. ` +
              `If the user reports an activity, acknowledge it and remind them to log it via the Log Activity page or confirm quantity so the app can store it.`,
          },
          ...history.slice(-8).map((h) => ({ role: h.role === 'user' ? 'user' : 'assistant', content: h.content })),
          { role: 'user', content: message },
        ],
      }),
      signal: AbortSignal.timeout(12000),
    });
    if (!res.ok) return null;
    const data = await res.json();
    const reply = data.choices?.[0]?.message?.content?.trim();
    return reply ? { reply, action: null } : null;
  } catch {
    return null; // any failure → rule-based fallback
  }
}
